# Fibonacci Series/dynamic programming

In [1]:
def fib(n,k=1):
    if n == 1:
        return 1
    if n == 2:
        return 1
    return fib(n-1, k) + k * fib(n-2, k)

In [4]:
import numpy as np
np.log(0.5)

-0.6931471805599453

In [9]:
A = np.array([[1,2,3], [2,4,6], [1,3,5]])

In [33]:
B = np.array([[[1],[2]],[[3],[4]]])

In [32]:
print(B)

[[[1]
  [2]]

 [[3]
  [4]]]


In [34]:
B.shape

(2, 2, 1)

In [44]:
test = np.array([[2,1,2],[1,3,3],[1,4,4]])

test2 = np.array([[1],[2],[3]])

In [46]:
test*test2

array([[ 2,  1,  2],
       [ 2,  6,  6],
       [ 3, 12, 12]])

In [35]:
np.array([[[1],[2]], [[3],[4]]]) # 2x2x1

array([[[1],
        [2]],

       [[3],
        [4]]])

In [22]:
np.array([[[1,2], [3,4]]]).shape

(1, 2, 2)

In [30]:
print(np.array([[[1,2], [3,4]]]))

[[[1 2]
  [3 4]]]


In [31]:
print(np.array([[[1],[2]], [[3],[4]]]))

[[[1]
  [2]]

 [[3]
  [4]]]


In [47]:
class MyNumbers:
    def __iter__(self):
        self.a = 1   # Initialize a counter attribute 'a' with the value 1
        return self  # Return the instance itself as the iterator

# Create an instance of MyNumbers
numbers = MyNumbers()

# when calling iter() the __iter__ method is invoked. 
num_iterator = iter(numbers)  

TypeError: iter() returned non-iterator of type 'MyNumbers'

You get an error b/c in Python, an iterator is expected to have a "__next__" method

In [48]:

class MyNumbers:
    def __iter__(self):
        self.b = 1   # Initialize a counter attribute 'b' with the value 1
        return self  # Return the instance itself as the iterator

    def __next__(self):
        x = self.b
        self.b += 1
        return x

# Create an instance of MyNumbers
numbers = MyNumbers()

# Get an iterator from the instance
num_iterator = iter(numbers)

print(next(num_iterator))  # Prints 1
print(next(num_iterator))  # Prints 2
print(next(num_iterator))  # Prints 3

1
2
3


In [49]:
num_iterator

In [50]:
import sklearn 

In [51]:
sklearn.set_config(display = "diagram")

In [54]:
from sklearn.pipeline import Pipeline
num_pipeline = Pipeline([
    ("impute", SimpleImputer(strategy = "median")),
    ("standardize", StandardSclaer()),
])

NameError: name 'SimpleImputer' is not defined

In [55]:
from sklearn.pipeline import Pipeline

num_pipeline = Pipeline([
    ("impute", SimpleImputer(strategy="median")),
    ("standardize", StandardScaler()),
])

NameError: name 'SimpleImputer' is not defined